### ISSUE TITLE
Site Fixes

### ISSUE THREAD

**Issue by aaron51198** [DigitalCarleton/omeka-bootswatch-themes#15]
Currently, I am unable to read the copyright part of the footer that reads "Ported by Alfredo Cosco from Bootswatch - Proudly powered by Omeka". I can only see it saying "From"

**Comment by aaron51198** [comment]
The separation between the title and the text feels wrong to me. I think it is because there is nothing dividing the text from the title in any meaningful way

**Comment by aaron51198** [comment]
Ok for some reason the whole site seemingly crashed. I got this error:
`exception 'InvalidArgumentException' with message 'Could not find file css/reader/bootstrap.min.css!' in /var/www/omeka-2.7/application/libraries/globals.php:1288
Stack trace:
#0 /var/www/omeka-2.7/application/libraries/globals.php(1247): web_path_to('css/reader/boot...')
#1 /var/www/omeka-2.7/application/libraries/globals.php(1193): src('reader/bootstra...', 'css', 'css', '2.7')
#2 /var/www/omeka-2.7/application/libraries/globals.php(1093): css_src('reader/bootstra...', 'css', '2.7')
#3 /var/www/omeka-2.7/themes/omeka-bootswatch-apjmason/common/header.php(26): queue_css_file('reader/bootstra...')
#4 /var/www/omeka-2.7/application/libraries/Omeka/View.php(114): include('/var/www/omeka-...')
#5 /var/www/omeka-2.7/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/var/www/omeka-...')
#6 /var/www/omeka-2.7/application/libraries/Zend/View/Helper/Partial.php(109): Zend_View_Abstract->render('common/header.p...')
#7 [internal function]: Zend_View_Helper_Partial->partial('common/header.p...', Array)
#8 /var/www/omeka-2.7/application/libraries/Zend/View/Abstract.php(350): call_user_func_array(Array, Array)
#9 /var/www/omeka-2.7/application/libraries/globals.php(1665): Zend_View_Abstract->__call('partial', Array)
#10 /var/www/omeka-2.7/application/libraries/globals.php(1665): Omeka_View->partial('common/header.p...', Array)
#11 /var/www/omeka-2.7/application/libraries/globals.php(1679): common('header', Array)
#12 /var/www/omeka-2.7/plugins/SimplePages/views/public/page/show.php(11): head(Array)
#13 /var/www/omeka-2.7/application/libraries/Omeka/View.php(114): include('/var/www/omeka-...')
#14 /var/www/omeka-2.7/application/libraries/Zend/View/Abstract.php(888): Omeka_View->_run('/var/www/omeka-...')
#15 /var/www/omeka-2.7/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('page/show.php')
#16 /var/www/omeka-2.7/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('page/show.php', NULL)
#17 /var/www/omeka-2.7/application/libraries/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#18 /var/www/omeka-2.7/application/libraries/Zend/Controller/Action/HelperBroker.php(277): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#19 /var/www/omeka-2.7/application/libraries/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#20 /var/www/omeka-2.7/application/libraries/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('showAction')
#21 /var/www/omeka-2.7/application/libraries/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#22 /var/www/omeka-2.7/application/libraries/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#23 /var/www/omeka-2.7/application/libraries/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#24 /var/www/omeka-2.7/application/libraries/Omeka/Application.php(73): Zend_Application->run()
#25 /var/www/omeka-2.7/index.php(23): Omeka_Application->run()
#26 {main}`
```
